local 139.59.65.241
port 1194
proto udp
dev tun0
ca ca.crt
cert server.crt
key server.key
dh dh.pem
#auth SHA512
auth SHA1
cipher AES-128-GCM
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.0.0
ifconfig-pool-persist ipp.txt
push "block-outside-dns"
status /var/log/openvpn/tun0.status
log /var/log/openvpn/tun0.log
keepalive 10 120
user nobody
group nogroup
persist-key
persist-tun
verb 3
crl-verify crl.pem
explicit-exit-notify
